# Generated by Django 5.2.16 on 2026-07-18 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicianGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_order', models.PositiveIntegerField(default=100)),
                ('min_per_session', models.PositiveIntegerField(blank=True, help_text='Warn when fewer members of this group are in on a session.', null=True)),
                ('is_locum_group', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_locum_group', True)), fields=('is_locum_group',), name='single_locum_group')],
            },
        ),
        migrations.CreateModel(
            name='Clinician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initials', models.CharField(max_length=5)),
                ('active', models.BooleanField(default=True)),
                ('leave_entitlement_sessions', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinician', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinicians', to='rota.cliniciangroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SessionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=8)),
                ('category', models.CharField(choices=[('CLINICAL', 'Clinical'), ('NON_CLINICAL', 'Non-clinical'), ('ABSENCE', 'Absence')], max_length=16)),
                ('colour', models.CharField(default='#8ecae6', max_length=7)),
                ('fairness_tracked', models.BooleanField(default=False)),
                ('counts_toward_entitlement', models.BooleanField(default=False)),
                ('allowed_clinicians', models.ManyToManyField(blank=True, related_name='restricted_session_types', to='rota.clinician')),
                ('allowed_groups', models.ManyToManyField(blank=True, related_name='restricted_session_types', to='rota.cliniciangroup')),
            ],
        ),
    ]
