# Generated by Django 5.2.16 on 2026-07-19 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DayNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('text', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CoverageRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('SESSION', 'Per session'), ('DAY', 'Per full day')], default='SESSION', max_length=8)),
                ('parts', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM'), ('BOTH', 'Both')], default='BOTH', help_text='Per-session rules only; ignored for full-day rules.', max_length=4)),
                ('weekdays', models.CharField(default='0,1,2,3,4', max_length=20)),
                ('count', models.PositiveIntegerField(default=1)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower fills first')),
                ('session_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_rules', to='rota.sessiontype')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_clinical_per_session', models.PositiveIntegerField(default=2)),
                ('leave_year_start_month', models.PositiveIntegerField(default=4)),
                ('leave_year_start_day', models.PositiveIntegerField(default=1)),
                ('open_weekdays', models.CharField(default='0,1,2,3,4', help_text='Comma-separated, Monday=0', max_length=20)),
                ('default_fill_session_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rota.sessiontype')),
            ],
        ),
        migrations.CreateModel(
            name='PatternSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('part', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('works', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_slots', to='rota.clinician')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('clinician', 'weekday', 'part', 'effective_from'), name='one_pattern_row_per_slot_per_date')],
            },
        ),
    ]
