# Generated by Django 5.2.16 on 2026-07-19 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0002_closedday_daynote_coveragerule_practicesettings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RotaEntryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('part', models.CharField(blank=True, max_length=2)),
                ('clinician_name', models.CharField(blank=True, max_length=100)),
                ('action', models.CharField(max_length=20)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='RotaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('part', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('manually_set', models.BooleanField(default=False)),
                ('allocation_group', models.UUIDField(blank=True, null=True)),
                ('fill_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rota_entries', to='rota.clinician')),
                ('session_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rota_entries', to='rota.sessiontype')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rota.site')),
            ],
            options={
                'ordering': ['day', 'part'],
                'constraints': [models.UniqueConstraint(fields=('day', 'part', 'clinician'), name='one_entry_per_cell')],
            },
        ),
    ]
