# Generated by Django 5.2.16 on 2026-07-19 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0003_rotaentrylog_rotaentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocumRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('part', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('status', models.CharField(choices=[('POSSIBLE', 'Possibly needed'), ('ADVERTISED', 'Advertised'), ('BOOKED', 'Booked')], default='POSSIBLE', max_length=10)),
                ('details', models.TextField(blank=True)),
                ('clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locum_bookings', to='rota.clinician')),
                ('rota_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locum_requirement', to='rota.rotaentry')),
                ('session_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rota.sessiontype')),
            ],
            options={
                'ordering': ['day', 'part'],
            },
        ),
    ]
