# Generated by Django 5.2.16 on 2026-07-19 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0005_leaverequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposer_day', models.DateField()),
                ('proposer_part', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('colleague_day', models.DateField()),
                ('colleague_part', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PROPOSED', 'Awaiting colleague'), ('ACCEPTED', 'Awaiting admin'), ('APPROVED', 'Applied'), ('DECLINED', 'Declined')], default='PROPOSED', max_length=10)),
                ('admin_comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('colleague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps_received', to='rota.clinician')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps_proposed', to='rota.clinician')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
