# Generated by Django 5.2.16 on 2026-08-22 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0006_swaprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinician',
            name='is_trainer',
            field=models.BooleanField(default=False, help_text='May supervise trainee mentoring sessions.'),
        ),
        migrations.AddField(
            model_name='coveragerule',
            name='frequency',
            field=models.CharField(choices=[('SLOT', 'Per slot'), ('WEEK', 'Per week'), ('MONTH', 'Per month (average)')], default='SLOT', max_length=6),
        ),
        migrations.AddField(
            model_name='coveragerule',
            name='months',
            field=models.CharField(blank=True, default='', help_text='Comma-separated month numbers (1-12); blank = all year', max_length=40),
        ),
        migrations.AddField(
            model_name='coveragerule',
            name='preferred_weekdays',
            field=models.CharField(blank=True, default='', help_text='Ordered comma-separated weekday numbers tried first (PER_WEEK/PER_MONTH rules), Monday=0', max_length=20),
        ),
        migrations.AddField(
            model_name='practicesettings',
            name='mentoring_session_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rota.sessiontype'),
        ),
        migrations.AddField(
            model_name='practicesettings',
            name='sdl_session_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rota.sessiontype'),
        ),
        migrations.AddField(
            model_name='practicesettings',
            name='vts_session_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rota.sessiontype'),
        ),
        migrations.AddField(
            model_name='rotaentry',
            name='companion_group',
            field=models.UUIDField(blank=True, help_text="Links the two clinicians' entries of a paired session (e.g. mentoring). Distinct from allocation_group.", null=True),
        ),
        migrations.AddField(
            model_name='sessiontype',
            name='blocks_same_day',
            field=models.ManyToManyField(blank=True, help_text='A clinician holding this type on a day is not auto-assigned any of these types the same day.', related_name='blocked_by_same_day', to='rota.sessiontype'),
        ),
        migrations.AddField(
            model_name='sessiontype',
            name='default_site',
            field=models.ForeignKey(blank=True, help_text='Auto-stamped on entries the fill engine creates for this type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rota.site'),
        ),
        migrations.AlterField(
            model_name='coveragerule',
            name='unit',
            field=models.CharField(choices=[('SESSION', 'Per session'), ('DAY', 'Per full day'), ('DAYPREF', 'Full day preferred (splittable)')], default='SESSION', max_length=8),
        ),
    ]
