# Generated by Django 5.2.16 on 2026-08-22 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0007_clinician_is_trainer_coveragerule_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraineeStageRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('FY2', 'FY2'), ('ST1', 'ST1'), ('ST2', 'ST2'), ('ST3', 'ST3')], max_length=3, unique=True)),
                ('vts_per_week', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('sdl_per_week', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('mentoring_per_week', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('vts_weekday', models.PositiveSmallIntegerField(blank=True, help_text='Monday=0; blank = VTS not anchored', null=True)),
                ('vts_part', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2, null=True)),
            ],
            options={
                'ordering': ['stage'],
            },
        ),
        migrations.CreateModel(
            name='TraineeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('FY2', 'FY2'), ('ST1', 'ST1'), ('ST2', 'ST2'), ('ST3', 'ST3')], max_length=3)),
                ('wte_percent', models.PositiveIntegerField(default=100)),
                ('placement_start', models.DateField()),
                ('placement_end', models.DateField()),
                ('clinician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_profile', to='rota.clinician')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainees', to='rota.clinician')),
            ],
        ),
    ]
