# Generated by Django 5.2.16 on 2026-08-22 21:51

from django.db import migrations

SEEDS = [
    ("FY2", 0, 2, 1, None, None),
    ("ST1", 1, 1, 1, 1, "AM"),
    ("ST2", 1, 1, 1, 1, "AM"),
    ("ST3", 1, 1, 1, 1, "PM"),
]


def seed(apps, schema_editor):
    TraineeStageRule = apps.get_model("rota", "TraineeStageRule")
    for stage, vts, sdl, ment, wd, part in SEEDS:
        TraineeStageRule.objects.update_or_create(
            stage=stage,
            defaults={"vts_per_week": vts, "sdl_per_week": sdl,
                      "mentoring_per_week": ment, "vts_weekday": wd,
                      "vts_part": part},
        )


def unseed(apps, schema_editor):
    apps.get_model("rota", "TraineeStageRule").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0008_traineestagerule_traineeprofile'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
