# Generated by Django 5.2.16 on 2026-08-22 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0009_seed_trainee_stage_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(help_text='Monday=0')),
                ('part', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM'), ('BOTH', 'Full day')], default='BOTH', max_length=4)),
                ('active_from', models.DateField()),
                ('active_until', models.DateField(blank=True, null=True)),
                ('interval_weeks', models.PositiveIntegerField(default=1, help_text="1 = weekly, 2 = fortnightly (anchored to the week of 'active from')")),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='rota.clinician')),
                ('session_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rota.sessiontype')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rota.site')),
            ],
            options={
                'ordering': ['clinician__name', 'weekday', 'part'],
            },
        ),
    ]
