# Generated by Django 5.2.16 on 2026-08-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0010_recurringcommitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineeprofile',
            name='requirements_tracked_from',
            field=models.DateField(blank=True, help_text='Requirements accrue from this date rather than placement start — set when the rota system starts tracking an in-progress placement. Blank means accrue from placement start.', null=True),
        ),
    ]
