# Generated by Django 5.2.16 on 2026-08-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0011_traineeprofile_requirements_tracked_from'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessiontype',
            options={'ordering': ['category', 'name']},
        ),
    ]
