# Generated by Django 5.2.16 on 2026-08-23 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0012_alter_sessiontype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternslot',
            name='weekday',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
