# Generated by Django 5.2.16 on 2026-08-23 21:29

from django.db import migrations

from rota import palette


def to_tints(apps, schema_editor):
    SessionType = apps.get_model("rota", "SessionType")
    for st in SessionType.objects.all():
        old = (st.colour or "").strip()
        if old in palette.TINTS:
            continue  # already migrated — leave legacy_colour alone
        st.legacy_colour = old[:7]
        st.colour = palette.nearest_tint(old)
        st.save(update_fields=["colour", "legacy_colour"])


def back_to_hex(apps, schema_editor):
    SessionType = apps.get_model("rota", "SessionType")
    for st in SessionType.objects.all():
        # Only rows `to_tints` actually captured have a legacy_colour to give
        # back. It skips rows that already held a tint key, and on a fresh
        # install it runs against an empty table, so every row created after
        # this migration has legacy_colour="". Assigning that unconditionally
        # would blank the colour of every session type added since deploy.
        st.colour = st.legacy_colour or st.colour
        st.save(update_fields=["colour"])


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0014_session_tint_palette'),
    ]

    operations = [migrations.RunPython(to_tints, back_to_hex)]
