# Generated by Django 5.2.16 on 2026-08-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0016_repair_legacy_colour_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontype',
            name='colour',
            field=models.CharField(choices=[('red-soft', 'Red — soft'), ('red-strong', 'Red — strong'), ('vermilion-soft', 'Vermilion — soft'), ('vermilion-strong', 'Vermilion — strong'), ('orange-soft', 'Orange — soft'), ('orange-strong', 'Orange — strong'), ('amber-soft', 'Amber — soft'), ('amber-strong', 'Amber — strong'), ('yellow-soft', 'Yellow — soft'), ('yellow-strong', 'Yellow — strong'), ('lime-soft', 'Lime — soft'), ('lime-strong', 'Lime — strong'), ('green-soft', 'Green — soft'), ('green-strong', 'Green — strong'), ('emerald-soft', 'Emerald — soft'), ('emerald-strong', 'Emerald — strong'), ('jade-soft', 'Jade — soft'), ('jade-strong', 'Jade — strong'), ('teal-soft', 'Teal — soft'), ('teal-strong', 'Teal — strong'), ('cyan-soft', 'Cyan — soft'), ('cyan-strong', 'Cyan — strong'), ('sky-soft', 'Sky — soft'), ('sky-strong', 'Sky — strong'), ('azure-soft', 'Azure — soft'), ('azure-strong', 'Azure — strong'), ('blue-soft', 'Blue — soft'), ('blue-strong', 'Blue — strong'), ('indigo-soft', 'Indigo — soft'), ('indigo-strong', 'Indigo — strong'), ('violet-soft', 'Violet — soft'), ('violet-strong', 'Violet — strong'), ('purple-soft', 'Purple — soft'), ('purple-strong', 'Purple — strong'), ('magenta-soft', 'Magenta — soft'), ('magenta-strong', 'Magenta — strong'), ('pink-soft', 'Pink — soft'), ('pink-strong', 'Pink — strong'), ('slate-soft', 'Rose — soft'), ('slate-strong', 'Rose — strong')], default='slate-soft', help_text='Session tint shown on the grid. All tints are contrast-checked.', max_length=32),
        ),
    ]
