# Generated by Django 5.2.16 on 2026-08-24 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0017_alter_sessiontype_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineeprofile',
            name='trainer',
            field=models.ForeignKey(blank=True, help_text="The trainee's named trainer for the placement. Only clinicians flagged as trainers are offered; when the named trainer is away the fill engine substitutes another trainer automatically.", limit_choices_to={'is_trainer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainees', to='rota.clinician'),
        ),
    ]
