# Generated by Django 5.2.16 on 2026-08-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0019_neutral_tint_and_rose_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinician',
            name='end_date',
            field=models.DateField(blank=True, help_text='Do not schedule after this date. Blank means no end bound.', null=True),
        ),
        migrations.AddField(
            model_name='clinician',
            name='start_date',
            field=models.DateField(blank=True, help_text='Do not schedule before this date. Blank means no start bound.', null=True),
        ),
    ]
