# Generated by Django 5.2.16 on 2026-08-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0020_clinician_date_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontype',
            name='pin_on_day_view',
            field=models.BooleanField(default=False, help_text='Show this type in its own block at the top of the day view. Use it for the roles someone would open the day view to check — Duty above all. Leave it off for the bulk of the rota.'),
        ),
    ]
