# Generated by Django 5.2.16 on 2026-09-02 17:28

import django.db.models.deletion
from django.db import migrations, models


def seed(apps, schema_editor):
    SessionType = apps.get_model("rota", "SessionType")
    Mapping = apps.get_model("rota", "BreatheLeaveMapping")
    defaults = {
        "holiday":  ("AL",   "Annual leave", "neutral-strong"),
        "sickness": ("SICK", "Sick",         "amber-strong"),
        "other":    ("OTH",  "Other leave",  "neutral-soft"),
    }
    for kind, (code, name, colour) in defaults.items():
        st = SessionType.objects.filter(code=code, category="ABSENCE").first()
        if st is None:
            # Holiday is the only one of the three that draws down a
            # clinician's leave entitlement (rota.services.leave.leave_summary
            # filters on this flag) — sickness and other leave do not.
            extra = {"counts_toward_entitlement": True} if kind == "holiday" else {}
            st, _ = SessionType.objects.get_or_create(
                name=name, defaults={"code": code, "category": "ABSENCE", "colour": colour, **extra})
        Mapping.objects.get_or_create(kind=kind, reason="", defaults={"session_type": st})


def unseed(apps, schema_editor):
    apps.get_model("rota", "BreatheLeaveMapping").objects.filter(reason="").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0021_sessiontype_pin_on_day_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreatheSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField()),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('ok', models.BooleanField(default=False)),
                ('n_requests', models.PositiveIntegerField(default=0)),
                ('n_absences', models.PositiveIntegerField(default=0)),
                ('n_sicknesses', models.PositiveIntegerField(default=0)),
                ('n_deduped', models.PositiveIntegerField(default=0)),
                ('n_unlinked', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Breathe sync run',
                'ordering': ['-started'],
            },
        ),
        migrations.AddField(
            model_name='clinician',
            name='breathe_employee_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='BreatheAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('half_start', models.BooleanField(default=False)),
                ('half_start_am_pm', models.CharField(blank=True, default='', max_length=2)),
                ('half_end', models.BooleanField(default=False)),
                ('half_end_am_pm', models.CharField(blank=True, default='', max_length=2)),
                ('kind', models.CharField(choices=[('holiday', 'Holiday'), ('other', 'Other leave'), ('sickness', 'Sickness')], max_length=10)),
                ('reason', models.CharField(blank=True, default='', max_length=100)),
                ('source_ids', models.CharField(blank=True, default='', max_length=100)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breathe_absences', to='rota.clinician')),
            ],
            options={
                'verbose_name': 'Breathe absence',
                'ordering': ['start_date', 'clinician_id'],
                'constraints': [models.UniqueConstraint(fields=('clinician', 'start_date', 'end_date', 'half_start', 'half_start_am_pm', 'half_end', 'half_end_am_pm'), name='breathe_absence_content_key')],
            },
        ),
        migrations.CreateModel(
            name='BreatheLeaveMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('holiday', 'Holiday'), ('other', 'Other leave'), ('sickness', 'Sickness')], max_length=10)),
                ('reason', models.CharField(blank=True, default='', max_length=100)),
                ('session_type', models.ForeignKey(limit_choices_to={'category': 'ABSENCE'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rota.sessiontype')),
            ],
            options={
                'verbose_name': 'Breathe leave mapping',
                'ordering': ['kind', 'reason'],
                'unique_together': {('kind', 'reason')},
            },
        ),
        migrations.RunPython(seed, unseed),
    ]
