# Generated by Django 5.2.16 on 2026-09-02 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0022_breathe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinician',
            name='leave_entitlement_sessions',
        ),
        migrations.RemoveField(
            model_name='practicesettings',
            name='leave_year_start_day',
        ),
        migrations.RemoveField(
            model_name='practicesettings',
            name='leave_year_start_month',
        ),
        migrations.RemoveField(
            model_name='sessiontype',
            name='counts_toward_entitlement',
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
