# Generated by Django 5.2.16 on 2026-09-03 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0023_remove_local_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='locumrequirement',
            name='covering',
            field=models.ForeignKey(blank=True, help_text='The clinician this locum stands in for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rota.clinician'),
        ),
        migrations.AlterField(
            model_name='locumrequirement',
            name='status',
            field=models.CharField(choices=[('POSSIBLE', 'Possibly needed'), ('APPROVED', 'Need approved'), ('ADVERTISED', 'Advertised'), ('BOOKED', 'Booked')], default='POSSIBLE', max_length=10),
        ),
    ]
