# Generated by Django 5.2.16 on 2026-09-04 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0024_locum_status_and_covering'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practicesettings',
            options={'verbose_name': 'practice settings', 'verbose_name_plural': 'practice settings'},
        ),
        migrations.AlterModelOptions(
            name='rotaentry',
            options={'ordering': ['day', 'part'], 'verbose_name': 'rota entry', 'verbose_name_plural': 'rota entries'},
        ),
        migrations.AlterModelOptions(
            name='rotaentrylog',
            options={'ordering': ['-at'], 'verbose_name': 'audit log entry', 'verbose_name_plural': 'audit log'},
        ),
        migrations.AlterModelOptions(
            name='traineeprofile',
            options={'verbose_name': 'trainee profile', 'verbose_name_plural': 'trainee profiles'},
        ),
        migrations.AlterField(
            model_name='clinician',
            name='active',
            field=models.BooleanField(default=True, help_text='Untick to remove someone from every eligibility pool while keeping their history — the alternative to deleting.'),
        ),
        migrations.AlterField(
            model_name='clinician',
            name='group',
            field=models.ForeignKey(help_text='Orders the grid and drives the group staffing warning.', on_delete=django.db.models.deletion.PROTECT, related_name='clinicians', to='rota.cliniciangroup'),
        ),
        migrations.AlterField(
            model_name='clinician',
            name='initials',
            field=models.CharField(help_text='Up to five characters — what the week grid shows.', max_length=5),
        ),
        migrations.AlterField(
            model_name='clinician',
            name='name',
            field=models.CharField(help_text='Full name, as it appears on the day view and reports.', max_length=100),
        ),
        migrations.AlterField(
            model_name='clinician',
            name='user',
            field=models.OneToOneField(blank=True, help_text='The login account for this clinician, if they have one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinician', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliniciangroup',
            name='display_order',
            field=models.PositiveIntegerField(default=100, help_text='Groups appear on the grid in this order, lowest first.'),
        ),
        migrations.AlterField(
            model_name='cliniciangroup',
            name='is_locum_group',
            field=models.BooleanField(default=False, help_text='Exactly one group: locums appear on the grid only in weeks they hold a session.'),
        ),
        migrations.AlterField(
            model_name='cliniciangroup',
            name='name',
            field=models.CharField(help_text='Partners, Salaried, GPST, Locums …', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='closedday',
            name='day',
            field=models.DateField(help_text='A bank holiday or closure. No sessions are expected and no warnings raised.', unique=True),
        ),
        migrations.AlterField(
            model_name='closedday',
            name='reason',
            field=models.CharField(blank=True, help_text='Shown on the grid header.', max_length=100),
        ),
        migrations.AlterField(
            model_name='coveragerule',
            name='count',
            field=models.PositiveIntegerField(default=1, help_text='How many placements per unit and frequency.'),
        ),
        migrations.AlterField(
            model_name='coveragerule',
            name='frequency',
            field=models.CharField(choices=[('SLOT', 'Per slot'), ('WEEK', 'Per week'), ('MONTH', 'Per month (average)')], default='SLOT', help_text='Per slot checks every session; per week and per month are quotas the fill engine spreads out.', max_length=6),
        ),
        migrations.AlterField(
            model_name='coveragerule',
            name='session_type',
            field=models.ForeignKey(help_text='What must be covered.', on_delete=django.db.models.deletion.CASCADE, related_name='coverage_rules', to='rota.sessiontype'),
        ),
        migrations.AlterField(
            model_name='coveragerule',
            name='unit',
            field=models.CharField(choices=[('SESSION', 'Per session'), ('DAY', 'Per full day'), ('DAYPREF', 'Full day preferred (splittable)')], default='SESSION', help_text='The shape of one placement: a session, a full day, or a full day if someone is free for both halves.', max_length=8),
        ),
        migrations.AlterField(
            model_name='coveragerule',
            name='weekdays',
            field=models.CharField(default='0,1,2,3,4', help_text='Days this rule applies on.', max_length=20),
        ),
        migrations.AlterField(
            model_name='daynote',
            name='text',
            field=models.CharField(help_text='Shown on the grid header and the day view, to everyone.', max_length=300),
        ),
        migrations.AlterField(
            model_name='locumrequirement',
            name='details',
            field=models.TextField(blank=True, help_text='Which agency, what rate, who you called.'),
        ),
        migrations.AlterField(
            model_name='practicesettings',
            name='default_fill_session_type',
            field=models.ForeignKey(blank=True, help_text='What assisted fill puts in any cell still empty after the rules, when you tick that box.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rota.sessiontype'),
        ),
        migrations.AlterField(
            model_name='practicesettings',
            name='mentoring_session_type',
            field=models.ForeignKey(blank=True, help_text='Leave blank to skip this trainee pass.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rota.sessiontype'),
        ),
        migrations.AlterField(
            model_name='practicesettings',
            name='min_clinical_per_session',
            field=models.PositiveIntegerField(default=2, help_text='Warn on the grid when fewer clinical GPs are in for a session.'),
        ),
        migrations.AlterField(
            model_name='practicesettings',
            name='open_weekdays',
            field=models.CharField(default='0,1,2,3,4', help_text='The days the surgery is open. The grid shows only these.', max_length=20),
        ),
        migrations.AlterField(
            model_name='practicesettings',
            name='sdl_session_type',
            field=models.ForeignKey(blank=True, help_text='Leave blank to skip this trainee pass.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rota.sessiontype'),
        ),
        migrations.AlterField(
            model_name='practicesettings',
            name='vts_session_type',
            field=models.ForeignKey(blank=True, help_text='Leave blank to skip this trainee pass.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rota.sessiontype'),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='category',
            field=models.CharField(choices=[('CLINICAL', 'Clinical'), ('NON_CLINICAL', 'Non-clinical'), ('ABSENCE', 'Absence')], help_text='Clinical counts toward minimum staffing; Absence marks someone as off.', max_length=16),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='code',
            field=models.CharField(help_text='What the grid cell shows. Keep it short and unique.', max_length=8),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='fairness_tracked',
            field=models.BooleanField(default=False, help_text='Shared out pro-rata to contracted sessions and reported on the fairness report.'),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='name',
            field=models.CharField(help_text='Shown in dropdowns and on the day view.', max_length=100, unique=True),
        ),
    ]
