# Generated by Django 5.2.16 on 2026-09-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0025_admin_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='colleague_comment',
            field=models.TextField(blank=True, help_text='What the colleague said when declining.'),
        ),
    ]
