# Generated by Django 5.2.16 on 2026-09-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0026_swaprequest_colleague_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontype',
            name='max_per_day',
            field=models.PositiveIntegerField(blank=True, help_text='Warn when more sessions of this type than this fall on one day (a full day counts as two). Blank means no limit.', null=True),
        ),
        migrations.AddField(
            model_name='sessiontype',
            name='max_per_session',
            field=models.PositiveIntegerField(blank=True, help_text='Warn on the week grid when more sessions of this type than this fall in one AM or PM. Blank means no limit.', null=True),
        ),
        migrations.AddField(
            model_name='sessiontype',
            name='max_per_week',
            field=models.PositiveIntegerField(blank=True, help_text='Warn when more sessions of this type than this fall in the week shown. Blank means no limit.', null=True),
        ),
    ]
