# Generated by Django 5.2.16 on 2026-09-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0027_sessiontype_ceiling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coveragerule',
            name='weekdays',
            field=models.CharField(blank=True, default='0,1,2,3,4', help_text='Days this rule applies on. Blank means every open day.', max_length=20),
        ),
    ]
