# Generated by Django 5.2.16 on 2026-09-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0028_coveragerule_weekdays_blank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinician',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='clinician',
            name='display_order',
            field=models.PositiveIntegerField(default=100, help_text='Rows within the group appear on the grid in this order, lowest first. Ties are alphabetical.'),
        ),
    ]
