# Generated by Django 5.2.16 on 2026-09-19 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0030_rotaentry_entered'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_weeks', models.PositiveSmallIntegerField(default=6, help_text='One every this many weeks, per clinician, counted from their last one.')),
                ('part', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM'), ('EITHER', 'Either')], default='EITHER', help_text='Which half-day it may take.', max_length=6)),
                ('weekdays', models.CharField(blank=True, default='', help_text='Days it may fall on. Blank means every open day. Monday=0.', max_length=20)),
                ('active_from', models.DateField(help_text='A clinician with none yet is due from this date.')),
                ('active_until', models.DateField(blank=True, help_text='Inclusive. Blank means open-ended.', null=True)),
                ('clinicians', models.ManyToManyField(help_text='Who owes it. Each must be eligible for the session type.', related_name='personal_requirements', to='rota.clinician')),
                ('session_type', models.ForeignKey(help_text='What each of them owes.', on_delete=django.db.models.deletion.PROTECT, related_name='personal_requirements', to='rota.sessiontype')),
            ],
            options={
                'verbose_name': 'personal requirement',
                'ordering': ['session_type__name', 'interval_weeks', 'id'],
            },
        ),
    ]
