# Generated by Django 5.2.16 on 2026-09-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0031_personalrequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontype',
            name='code',
            field=models.CharField(help_text='What the grid cell shows. Six characters is what fits — a longer code is clipped there, and the full name shows only on hover. Keep it unique: two types with one code are indistinguishable on the grid.', max_length=8),
        ),
    ]
