# Generated by Django 5.2.16 on 2026-09-27 19:19

from django.db import migrations, models


def backfill(apps, schema_editor):
    """Rows written before the column existed: their actor's email, while
    the login still exists to read it from."""
    RotaEntryLog = apps.get_model("rota", "RotaEntryLog")
    for row in RotaEntryLog.objects.filter(actor__isnull=False, actor_name="").select_related("actor"):
        row.actor_name = row.actor.email
        row.save(update_fields=["actor_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0032_sessiontype_code_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotaentrylog',
            name='actor_name',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
