# Generated by Django 5.2.16 on 2026-09-05 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('BUG', "Something's wrong"), ('IDEA', 'An idea')], max_length=4)),
                ('message', models.TextField()),
                ('page', models.CharField(blank=True, help_text='Path and query of the page the report was sent from.', max_length=300)),
                ('viewport', models.CharField(blank=True, help_text='Width x height in CSS pixels.', max_length=20)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SEEN', 'Seen'), ('DONE', 'Done')], default='NEW', max_length=4)),
                ('admin_note', models.TextField(blank=True, help_text='For admins only — never sent.')),
                ('reply', models.TextField(blank=True, help_text='Sent to the reporter by Send reply.')),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
