# Generated by Django 5.2.16 on 2026-09-04 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'login account', 'verbose_name_plural': 'login accounts'},
        ),
    ]
