# Generated by Django 5.2.16 on 2026-09-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_login_account_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_link_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
