# Generated by Django 5.2.16 on 2026-09-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_password_link_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_rota_admin',
            field=models.BooleanField(default=False, help_text='Can use this admin, publish weeks, run the fill and approve requests.', verbose_name='admin status'),
        ),
    ]
