# Generated by Django 5.2.17 on 2026-09-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_email_case_insensitive"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="oidc_sub",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Set at their first sign-in with the practice account. Clear it only if their login on the HR system was replaced by a new one.",
                max_length=255,
                verbose_name="practice account id",
            ),
        ),
    ]
